server:
  port: 8080

logging:
  config: classpath:logback-config.xml

spring:
  application:
    name: learn-spring-boot
  datasource:
    username: root
    password: toor
    url: jdbc:mysql://127.0.0.1:3306/userdb
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: ''
    pool:
      max-active: 200
      max-wait: -1
      max-idle: 10
      min-idle: 0
    timeout: 1000

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    listener:
      simple:
        #acknowledge-mode: manual #设置确认模式手工确认
        concurrency: 3 #消费者最小数量
        max-concurrency: 10 # 消费者最大数量


  aop:
    proxy-target-class: True

