server:
  port: 8033

spring:
  application:
    name: learn-spring-boot
  datasource:
    username: root
    password: toor
    url: jdbc:mysql://mysql:3306/userdb
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  aop:
    proxy-target-class: True

